"""
Data models for the News Intelligence pipeline.
"""

from __future__ import annotations
from dataclasses import dataclass, field, asdict
from datetime import datetime
from typing import Optional
import hashlib, json


@dataclass #to make our lives easier (not initializing __init__.py and other functions)
class RawArticle: 
    id: str = "" #id of the article
    canonical_url: str = "" #official url of the article
    source: str = "" #where did the article come from (Website)
    category: str = "" #category of the article
    feed_url: str = "" #url of the feed
    title: str = "" #title of the article
    summary: str = "" #article summary (will be generated by AI)
    full_text: str = "" #full text (we don't want to store this)
    author: str = "" #author of the article
    tags: list[str] = field(default_factory=list) #tags of the article
    top_image: str = "" #the image
    published_at: Optional[datetime] = None #time published
    collected_at: datetime = field(default_factory=datetime.utcnow) #time collected
    word_count: int = 0 #word count
    extraction_method: str = "" #method of extraction
    extraction_success: bool = False #if extraction of the text is successful
    extraction_error: str = "" #error 

    def __post_init__(self):
        if self.canonical_url and not self.id: #if self id doesn't exist but article url exists
            self.id = hashlib.sha256(self.canonical_url.encode()).hexdigest()[:16] #16 characters id
        if self.full_text:
            self.word_count = len(self.full_text.split())

    def to_dict(self) -> dict: #converting to the dict
        d = asdict(self)
        for k in ("published_at", "collected_at"):
            if d[k] is not None:
                d[k] = d[k].isoformat()
        return d

    def to_json(self, indent: int = 2) -> str: #converting to the json
        return json.dumps(self.to_dict(), ensure_ascii=False, indent=indent) 

    @property #we can call .has_full_text
    def has_full_text(self) -> bool: #boolean function. If word count>50 and full text exists, the function returns True
        return bool(self.full_text) and self.word_count > 50

    @property
    def content_preview(self) -> str: #enabling preview
        text = self.full_text or self.summary  #
        return text[:300].strip() + ("…" if len(text) > 300 else "")


@dataclass
class CollectionResult:
    articles: list[RawArticle] = field(default_factory=list) #list of articles
    feeds_attempted: int = 0 #attempted feeds
    feeds_succeeded: int = 0 #succeeded feeds
    feeds_failed: int = 0 #failed feeds (attempted - succeeded)
    duplicates_removed: int = 0 #number of duplicated removed
    extraction_failures: int = 0 #number of extraction failures
    run_started_at: datetime = field(default_factory=datetime.utcnow) #pipeline start time
    run_ended_at: Optional[datetime] = None #pipeline end time

    @property
    def total_articles(self) -> int: #returning the article number
        return len(self.articles)

    @property
    def extraction_success_rate(self) -> float:
        if not self.articles:
            return 0.0
        return sum(1 for a in self.articles if a.extraction_success) / len(self.articles) #calculating the extraction success rate

    def summary_dict(self) -> dict: #returning the results in a dict format
        return {
            "total_articles": self.total_articles, #number of articles
            "feeds_attempted": self.feeds_attempted, 
            "feeds_succeeded": self.feeds_succeeded,
            "feeds_failed": self.feeds_failed,
            "duplicates_removed": self.duplicates_removed,
            "extraction_failures": self.extraction_failures,
            "extraction_success_rate": round(self.extraction_success_rate * 100, 1),
            "run_started_at": self.run_started_at.isoformat(),
            "run_ended_at": self.run_ended_at.isoformat() if self.run_ended_at else None,
        }

#DONE